export default {
	AWAITING_CREATION: 'AWAITING_CREATION',
	IS_CREATING: 'IS_CREATING',
	AWAITING_FUNDING: 'AWAITING_FUNDING',
	IS_FUNDING: 'IS_FUNDING',
	AWAITING_ACTIVATION: 'AWAITING_ACTIVATION',
	VALIDATING: 'VALIDATING',
	CREATING_ERROR: 'CREATING_ERROR',
	FUNDING_ERROR: 'FUNDING_ERROR'
}